### ISSUE TITLE
infer the ticket number based on data in the branch name

### ISSUE THREAD

**Issue by ingshtrom** [ingshtrom/stash-creview#3]
if I have a branch called "feature/TICK-1234-do-something", it should recognize that the ticket is "TICK-1234"

**Comment by jacobsmith** [comment]
Pipe Dream:
I can set a regex for what I want it to match against (so that it is useful in many different naming schemes)

```bash
parseLabelRegex : TICK-\d{4}
```

**Comment by ingshtrom** [comment]
That could pretty easily be done in the first iteration of the feature. I
could add it to the repo config file since everyone should be using the
same naming scheme.
